# Generated by Django 5.0.4 on 2024-04-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catagory_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.BooleanField(default=False, help_text='0-default,1-Trending'),
        ),
    ]
